spring:
  application:
    name: dnd-character
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: admin
    password: revature
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 5000
